version: "3.9"

services:
  file-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-service
    environment:
      - PGENGINE=django.db.backends.postgresql
      - PGDATABASE=fileDB
      - PGUSER=nugress_manager
      - PGPASSWORD=manager**2020
      - PGHOST=postgresDB
      - PGPORT=5432
      - DEBUG=1
      - SECRET_KEY="$wi+si&u@cvep!_q!xl9u!oznt0w$sf%ps71(_fcc22g#)v"
      - ALLOWED_HOSTS="http://localhost, bregoh-filemanager.herokuapp.com"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"

networks:
  default:
    external: true
    name: service-network
