# Generated by Django 4.0.2 on 2022-02-27 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesManagement',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/uploads')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'filesmanagement',
            },
        ),
        migrations.CreateModel(
            name='FileLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(max_length=200)),
                ('is_expired', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filelinks', to='api.filesmanagement')),
            ],
            options={
                'db_table': 'filelinks',
            },
        ),
    ]
