# Generated by Django 4.0.2 on 2022-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelinks',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
