# Generated by Django 4.0.2 on 2022-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filelinks_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelinks',
            name='link_visit',
            field=models.IntegerField(null=True),
        ),
    ]
