# Generated by Django 4.0.2 on 2022-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filesmanagement_file_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelinks',
            name='link_visit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='filesmanagement',
            name='file_visit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
