# Generated by Django 4.0.2 on 2022-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_filelinks_link_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelinks',
            name='link_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filesmanagement',
            name='file_visit',
            field=models.IntegerField(default=0),
        ),
    ]
