# Generated by Django 4.0.2 on 2022-02-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_filelinks_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelinks',
            name='created',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='filesmanagement',
            name='created',
            field=models.DateField(default=datetime.date),
        ),
    ]
