# Generated by Django 4.0.2 on 2022-02-28 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_filelinks_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('os', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'useragent',
            },
        ),
    ]
