# Generated by Django 4.0.2 on 2022-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_useragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='link_id',
            field=models.UUIDField(null=True),
        ),
    ]
