# Generated by Django 4.0.2 on 2022-02-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_useragent_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelinks',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filesmanagement',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
