# Generated by Django 4.0.2 on 2022-02-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_filelinks_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmanagement',
            name='file_visit',
        ),
    ]
